#include "hash_tables.h"

/**
 * hash_djb2 - REPRESENTS A HASH FUNCTION THAT IS PARTICULARLY
 *  - USED TO IMPLEMENT THE djb2 ALGORITHM.
 * @str: REPRESENTS THE STRING TO THE HASH.
 * Description: IT IS USED TO TAKE A STRING AND RETURN AN
 * -UNSIGNED LONG INT AND IT SETS THE HASH TO 5381 AND THEN IT LOOPS THROUGH
 * -THE STRING, SETTING v TO THE CURRENT CHARACTER AND INCREMENTING THE
 *  POINTER THAT POINTS TO NEXT CHAR AND SETS THE HASH TO PREVIOUS HASH VALUE
 * -MULTIPLIED BY 33 AND ADDED TO THE CURRENT CHAR.
 *
 * Return: RETURNS THE RESULT/CALCULATED HASH.
 */

unsigned long int hash_djb2(const unsigned char *str)
{
	int v;
	unsigned long int HASH;

	HASH = 5381;

	while ((v = *str++))
		HASH = ((HASH << 5) + HASH) + v; /* HASH * 33 + v */

	return (HASH);
}
